// src/components/TodoItem.svelte
<script lang="ts">
  import type { Todo } from "@prisma/client"
  import { trpc } from "../utils/trpc"

  export let todo: Todo
  export let onDelete = () => {}

  let updatedTodo: Todo = structuredClone(todo)

  const debounce = (fn: () => any, delay: number) => {
    let timerId: NodeJS.Timeout | null = null

    return () => {
      if (timerId) {
        clearTimeout(timerId)
      }

      timerId = setTimeout(() => {
        fn()
      }, delay)
    }
  }

  const getTodoDiff = (): boolean => {
    if (todo.todo.trim() != updatedTodo.todo.trim()) return true
    else if (todo.finished != updatedTodo.finished) return true
    else if (todo.deadline?.toUTCString() != todo.deadline?.toUTCString())
      return true
    else return false
  }

  const updateTodo = debounce(async () => {
    const diff = getTodoDiff()

    if (!diff) return

    updatedTodo = await trpc.updateTodo.mutate({
      id: todo.id,
      deadline: todo.deadline,
      finished: todo.finished,
      todo: todo.todo,
    })
  }, 100)

  const deleteTodo = async () => {
    onDelete()
    await trpc.removeTodo.mutate({ id: todo.id })
  }

  $: if (todo) {
    updateTodo()
  }
</script>

<div class="flex flex-row items-start gap-x-4 group relative">
  <input
    type="checkbox"
    class="flex-none rounded-xl w-3.5 h-3.5 mt-1"
    bind:checked={todo.finished}
  />
  <div
    contenteditable="true"
    data-ph="Type here"
    class={`flex-1 w-full outline-none focus:border-b border-neutral-200 empty:before:content-[attr(data-ph)] before:text-neutral-500 before:cursor-text ${
      todo.finished ? "line-through" : ""
    }`}
    spellcheck="false"
    bind:innerText={todo.todo}
  />
  <div
    class="group-hover:flex flex-row items-center absolute top-1/2 transform -translate-y-1/2 hidden right-1"
  >
    <button
      type="button"
      class="rounded-full transition duration-200 hover:bg-black/5 p-1"
      on:click={() => {
        deleteTodo()
      }}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke-width="1.5"
        class="w-4 h-4 stroke-red-700"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"
        />
      </svg>
    </button>
  </div>
</div>

// src/components/TodoItem.tsx
"use client"

import { updateTodo } from "@/app/actions"
import { inLoadingAtom } from "@/utils/atoms"
import { Todo } from "@prisma/client"
import { useSetAtom } from "jotai"
import { FC, useEffect, useState } from "react"

function debounce(func: (...args: any[]) => any, delay: number) {
  let timerId: NodeJS.Timeout

  return (...args: Parameters<typeof func>) => {
    clearTimeout(timerId)

    timerId = setTimeout(() => {
      func.call(undefined, ...args)
    }, delay)
  }
}

const debouncedUpdateTodo = debounce((todo: Todo) => {
  updateTodo(todo).then((v) => console.log("Updated", v))
}, 100)

const TodoItem: FC<{
  initialTodo: Todo
  onRemove?: (...args: any[]) => any
  editable?: boolean
}> = ({ initialTodo, onRemove, editable = true }) => {
  const [todo, setTodo] = useState<Todo>({ ...initialTodo })
  const setInLoading = useSetAtom(inLoadingAtom)

  useEffect(() => {
    debouncedUpdateTodo(todo)
  }, [todo])

  return (
    <div className="relative flex flex-row items-center gap-x-1">
      {onRemove && (
        <button
          className="absolute right-0 ml-2"
          type="button"
          onClick={async () => {
            setInLoading(true)
            await onRemove()
            setInLoading(false)
          }}
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth={1.5}
            className="h-4 w-4 stroke-neutral-400 transition duration-300 hover:stroke-red-500"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"
            />
          </svg>
        </button>
      )}
      <input
        type="checkbox"
        className="h-4 w-4 rounded"
        checked={todo.finished}
        disabled={!editable}
        onChange={(event) => {
          setTodo((previousTodo) => ({
            ...previousTodo,
            finished: event.target.checked,
          }))
        }}
      />
      <input
        type="text"
        className={`h-6 w-full border-0 focus:ring-0 ${
          todo.finished ? "line-through" : ""
        }`}
        placeholder="할 일 적기"
        value={todo.todo}
        disabled={!editable}
        onInput={(event) => {
          const target = event.target
          if (target instanceof HTMLInputElement)
            setTodo((previousTodo) => ({
              ...previousTodo,
              todo: target.value,
            }))
        }}
      />
    </div>
  )
}

export default TodoItem
